# Generated by Django 4.2.4 on 2023-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('surname', models.CharField(max_length=70, null=True)),
                ('age', models.IntegerField(null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('self_description', models.TextField(null=True)),
            ],
        ),
    ]
